version: "3"
services:
  nginx:
    image: "nginx:latest"
    container_name: cism_front
    volumes:
      - ./:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /code
    ports:
      - "9000:80"
    command: bash /code/start.sh