version: "3"
services:
  nginx:
    image: "ubuntu:latest"
    container_name: cism_front
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /code
    ports:
      - "9000:80"
    command: sh /code/start.sh