version: "3"

services:
  nginx:
    image: nginx
    container_name: cism_front
    volumes:
      - /home/amvara/projects/cism/dist/:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9002:80"